# The visible text of site.
# © 2017-2019 Cotes Chung
# MIT License

title: "Chirpy"
slogan: "A text-based Jekyll theme."
description: "A text-based Jekyll theme." # RSS feed
logo_url: "/assets/img/sample/avatar.jpg"

comments: true  # boolean type, the gobal switch of posts' comments.

toc: true  # boolean type, gobal switch for ToC in posts.

pv: false   # Google Analytics pageviews, DO NOT enable it.

lang: en   # Must be 'en' or 'zh'

tabs:
  - { name: { zh: "首 页", en: "Home" } }
  - { name: { zh: "分 类", en: "Categories" }, path: tabs, url: categories }
  - { name: { zh: "标 签", en: "Tags" }, path: tabs, url: tags }
  - { name: { zh: "归 档", en: "Archives" }, path: tabs, url: archives }
  - { name: { zh: "关 于", en: "About" }, path: tabs, url: about }

panel:
  lastmod:
    { en: "Recent Update", zh: "最近更新" }
  tags:
    { en: "Trending Tags", zh: "热门标签" }
  toc:
    { en: "Contents", zh: "目录" }

search_hint: { en: "Search", zh: "搜索" } # text show on search bar
